#!/usr/bin/env bash

# This script helps run the MLIR toy examples.

set -e
ROOT="$(realpath $(dirname $(dirname $0)))"

# Color settings
Bold='\033[1m'
BRed='\033[1;31m'
BGreen='\033[1;32m'
NC='\033[0m' # No Color

# Log an error.
err() {
    printf "${BRed}Error${NC}: $1\n" >&2
    exit 1
}

# Log info.
info() {
    printf "${BGreen}Info${NC}: $1\n" >&1
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
    if ! "$@"; then err "command failed: $*"; fi
}

run_ch1() {
    info "Building Toy chapter 1."
    make ch1
    info "Running Toy chapter 1 example."
    "${ROOT}/build/ch1/toy_ch1" "${ROOT}/examples/ch1/ast.toy" -emit=ast
}

main() {
    case $1 in
        "ch1")
            ensure run_ch1;;
        *)
            echo 'Expected: "ch1"';;
    esac
}

main "$@" || exit 1
